//LISTING ACTIONS
export const FETCH_ALL_LISTINGS = "FETCH_ALL_LISTINGS";
export const FETCH_ALL_LISTINGS_BY_CATEGORY = "FETCH_ALL_LISTINGS_BY_CATEGORY"
export const FETCH_ALL_LISTINGS_BY_CATEGORY_ERROR = "FETCH_ALL_LISTINGS_BY_CATEGORY_ERROR"
export const FETCH_LISTING_BY_ID = "FETCH_LISTING_BY_ID";
export const CREATE_LISTING = "CREATE_LISTING"
export const DELETE_LISTING = "DELETE_LISTING"
export const DELETE_LISTING_ERROR = "DELETE-LISTING_ERROR"
export const FETCH_USER_BY_ID = "FETCH_USER_BY_ID";
// AUTH ACTIONS
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const SIGNUP_USER = "SIGNUP_USER"
export const SIGNUP_ERROR = "SIGNUP_ERROR"